const AUTH_ACTION_TYPES = {
    USER_UPDATED: '@AUTH/USER_UPDATED',
    USER_SIGNED_IN: '@AUTH/USER_SIGNED_IN',
    USER_SIGNED_OUT: '@AUTH/USER_SIGNED_OUT',
    AUTHENTICATION_STARTED: '@AUTH/AUTHENTICATION_STARTED',
    AUTHENTICATION_FINISHED: '@AUTH/AUTHENTICATION_FINISHED',
};

export default AUTH_ACTION_TYPES;
