const CART_ACTIONS_TYPES = {
    CART_CLEANED: '@CART/CART_CLEANED',
    ITEM_ADDED: '@CART/ITEM_ADDED',
    ITEM_REMOVED: '@CART/ITEM_REMOVED',
    ITEM_QUANTITY_INCREASED: '@CART/ITEM_QUANTITY_INCREASED',
    ITEM_QUANTITY_DECREASED: '@CART/ITEM_QUANTITY_DECREASED',
};

export default CART_ACTIONS_TYPES;
