const ESTABLISHMENTS_ACTIONS_TYPES = {
    ESTABLISHMENT_LOADED: '@ESTABLISHMENTS/ESTABLISHMENT_LOADED',
    ESTABLISHMENTS_LOADED: '@ESTABLISHMENTS/ESTABLISHMENTS_LOADED',
    ESTABLISHMENTS_LOADING: '@ESTABLISHMENTS/ESTABLISHMENTS_LOADING',
};

export default ESTABLISHMENTS_ACTIONS_TYPES;
