const ORDERS_ACTIONS_TYPES = {
    ORDER_LOADED: '@ORDERS/ORDER_LOADED',
    ORDER_CREATED: '@ORDERS/ORDER_CREATED',
    ORDERS_LOADED: '@ORDERS/ORDERS_LOADED',
    ORDERS_LOADING: '@ORDERS/ORDERS_LOADING',
};

export default ORDERS_ACTIONS_TYPES;
